#!/usr/bin/env bash

# --- BASH SETUP --- #
alias ls='ls --color=auto'
alias ll='ls -al --color=auto'
alias l='ls -a1 --group-directories-first'
alias c='clear'

alias rbash='source ~/.bashrc'
alias bashcfg='vim ~/kadevrc/'
alias kubecfg='vim ~/.kube/config'
alias icopy='xclip -selection c -rmlastnl'
alias notes='cd ~/.notes && vim'
