#!/usr/bin/env bash
function low_brightness() {
  [ "$1" = on ] && xrandr --output DVI-D-0 --brightness 0.6
  [ "$1" = off ] && xrandr --output DVI-D-0 --brightness 1
}

function brightness() {
    if [ -z "$1" ]; then
      echo No brightness value provided, pleasant range is 0 to 1.5
    else
      eval 'xrandr --output DVI-D-0 --brightness "$1"'
    fi
}
