#!/usr/bin/env bash
if [[ $TERM == xterm ]]; then TERM=xterm-256color; fi

function tmux-ns() {
    if [ -z "$1" ]; then
        TITLE="$1"
    else
        TITLE="untitled"
    fi

    tmux new-session -s $1
}

function tmux-s() {
    if [ -z "$1" ]; then
        TITLE="$1"
    else
        TITLE="untitled"
    fi

    tmux new-session -d -s $1
}

function tmux-w() {
    if [ -z "$1" ]; then
        TITLE="$1"
    else
        TITLE="untitled"
    fi

    tmux new-window -n $1
}

function tmux-rw() {
    if [ -z "$1" ]; then
        TITLE="$1"
    else
        TITLE="untitled"
    fi

    tmux rename-window $1
}

alias tmux-k='tmux kill-server'
alias rtmux='tmux source-file ~/.tmux.conf'

alias tmux-setup='tmux-rw code && tmux-w code:ref && tmux-w VPN && tmux-w background && tmux-w doc && tmux-w misc'
