#!/usr/bin/env bash
# --- PULSE AUDIO SETUP --- #
alias set-phone='pactl set-sink-port 0 analog-output-headphones'
alias set-speaker='pactl set-sink-port 0 analog-output-speaker'

mic_on() {
    pactl load-module module-loopback latency_msec=1
}

mic_off() {
    pactl unload-module module-loopback
}

# GM4   MAC ADDR :: 20:10:09:16:0C:5F
# AZ09  MAC ADDR :: A8:99:DC:47:BD:FA

alias gm4-on='bluetoothctl unblock 20:10:09:16:0C:5F && bluetoothctl -- connect 20:10:09:16:0C:5F'
alias gm4-off='bluetoothctl -- disconnect 20:10:09:16:0C:5F && bluetoothctl block 20:10:09:16:0C:5F'

alias az-on='bluetoothctl unblock A8:99:DC:47:BD:FA && bluetoothctl -- connect A8:99:DC:47:BD:FA'
alias az-off='bluetoothctl -- disconnect A8:99:DC:47:BD:FA && bluetoothctl block A8:99:DC:47:BD:FA'
