#!/usr/bin/env bash

# --- BASH SETUP --- #
alias ls='exa -a1 --group-directories-first --icons'
alias ll='ls -al'
alias l='ls'

alias c='clear'
alias cc='cclear'
alias cclear='clear; echo -e "\033c\e[3J"'

alias printpath="echo $PATH | tr : '\n'"

alias rbash='source ~/.bashrc'
alias kadevcfg='vim ~/kadevrc/'
alias kubecfg='vim ~/.kube/config'
alias notes='vim ~/projects/notes.md'
alias i3cfg='vim ~/.config/i3/config'

alias icopy='xclip -selection c -rmlastnl'
alias pbcopy='xclip -sel clip'

# windows specific commands
alias shell:startup='cd "/mnt/c/Users/aron.koffler/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup"' 
alias winfolder='cd "/mnt/c/Users/aron.koffler/wsl"'

# notebook brightness
alias xlight='xrandr --output HDMI-0 --brightness'
alias aoclight='xrandr --output DP-4 --brightness'
