#!/usr/bin/env bash

# --- BASH SETUP --- #
alias ls='exa -a1 --group-directories-first --icons'
alias ll='ls -al'
alias l='ls'

alias c='clear'

alias cat='batcat'

alias printpath="echo $PATH | tr : '\n'"

alias rbash='source ~/.bashrc'
alias kadevcfg='vim ~/kadevrc/'
alias kubecfg='vim ~/.kube/config'
alias notes='vim ~/projects/notes.md'
alias i3cfg='vim ~/.config/i3/config'

alias icopy='xclip -selection c -rmlastnl'
alias pbcopy='xclip -sel clip'
