#!/usr/bin/env bash

export PATH="$PATH:$HOME/projects/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:/usr/local/go/bin"
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export PATH="$HOME/.local/share/nvim/mason/packages/jdtls:$PATH"

